checking that required env variables are set before executing deployment scripts...

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,6 +10,26 @@ pool: Default
 
 steps:
 - script: |
+    echo "Preventing calamity. Please wait while environment variables are verified..."
+    # ENSURE ENVIRONMENT VARIABLES EXIST, OTHERWISE CRASH
+    # IT'S CRITICAL THIS EXISTS OTHERWISE THE DEPLOYING SERVER WILL GET NUKED!!
+    if [ -z "$(ckan_log_path)" ||
+        -z "$(ckan_port)" ||
+        -z "$(ckan_site_url)" ||
+        -z "$(ckan_tag)" ||
+        -z "$(ckanexts_path)" ||
+        -z "$(docker_exts_path)" ||
+        -z "$(docker_venv_path)" ||
+        -z "$(docker_path)" ||
+        -z "$(ext_name)"] 
+    then
+        echo "Required environment variables not set! Exiting to prevent catastrophic behavior!"
+        exit 1
+  continueOnError: false
+  displayName: 'Environment Variable check'
+
+steps:
+- script: |
 
     echo Cloned repo into $(Agent.BuildDirectory)/s/
     echo Repo contents:
